config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'static_pages/home'
  resources :brands
  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :price, presence: true
  belongs_to :brand
  validates_numericality_of :price, :less_than_or_equal_to => 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :find_brand, only:[:show, :edit, :update, :destroy]

  def index
    @brands = Brand.all
  end

  def show
  end

  def new
    @brand = Brand.new(params[:id])
  end

  def create
    @brand = Brand.new(brand_params)

    if @brand.save
      flash[:success] = "Brand created."
      redirect_to @brand
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @brand.update_attributes(brand_params)
      redirect_to @brand
    else
      render 'edit'
    end
  end

  def destroy
    @brand.destroy
    redirect_to brands_path
  end

  private
    def find_brand
      @brand = Brand.find(params[:id])
    end

    def brand_params
      params.require(:brand).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only:[:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    @total = @products.sum(&:price)
  end

  def show
  end

  def new
    @product = Product.new(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      redirect_to @product
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end


  private
    def find_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :brand_id, :description, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/brands/_form.html.erb
<%= form_for @brand do |b| %>

  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@brand.errors.count, "error") %>.
      </div>
      <ul>
      <% @brand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <%= b.label :name, for: "name" %>
      <%= b.text_field :name, id:"name", class: "form-control",
                              placeholder: "New brand"%>
    </div>
  </div>


  <P>
    <%= b.submit "Save", class:"btn btn-default"%>
  </P>

<% end %>

app/views/brands/edit.html.erb
<div class="row">
  <div>
    <h1>Editing <%= @brand.name %></h1>
    <%= link_to 'Back', brand_path %>
    <hr>
  </div>

  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/brands/index.html.erb
<div class="row">
  <div>
    <h1 class="text-title">List of Brands</h1>
    <%= link_to "Add Brand", new_brand_path %>
  </div>

  <div>
    <hr>
    <% @brands.each do |b| %>
      <u clas:"text-upercasse"><%= link_to b.name, b%></u><br>
    <% end %>
  </div>
</div>

app/views/brands/new.html.erb
<div class="row">
  <div>
    <h1>New brand</h1>
    <%= link_to 'Back', brands_path %>
    <hr>
  </div>

  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/brands/show.html.erb
<div class="row">
  <div>
    <h1>Brand "<%= @brand.name %>"</h1>
    <%= link_to 'Brands list', brands_path %> | <%= link_to 'Edit', edit_brand_path %> |
    <%= link_to 'Delete', @brand, method: :delete, data: { confirm: 'Are you sure to delete this brand?' }%>
    <hr>
  </div>

  <div>
    <%= @brand.name %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MicheladaTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'partials/header' %>
    <div class="container margin-top">
      <div class="margin-top">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <%= yield %>
      <!-- <%= debug(params) if Rails.env.development? %> -->
      <%= render 'partials/footer' %>
    </div>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">
  <small>
    By <a href="https://twitter.com/benjamin_pena">Benjamín Peña (ElBenjas)</a>
  </small>
</footer>

app/views/partials/_formBrands.html.erb
<%= form_for @brand do |b| %>

  <div class="form-group">
    <%= b.label :name, for: "name" %>
    <%= b.text_field :name, id:"name", class: "form-control",
                            placeholder: "New brand"%>
  </div>

  <P>
    <%= b.submit "Save", class:"btn btn-default"%>
  </P>

<% end %>

app/views/partials/_formProducts.html.erb
<%= form_for @product do |p| %>

  <div class="form-group">
    <%= p.label :name, for: "name" %>
    <%= p.text_field :name, id:"name", class: "form-control",
                            placeholder: "Name"%>
  </div>

  <div class="form-group">
    <%= p.label :brand, for: "brand" %>
    <%= p.text_field :brand, id:"brand", class: "form-control",
                            placeholder: "Brand"%>
  </div>

  <div class="form-group">
    <%= p.label :descriptions, for: "description" %>
    <%= p.text_area :name, id:"description", class: "form-control",
                            placeholder: "Description"%>
  </div>

  <div class="form-group">
    <%= p.label :price, for: "price" %>
    <%= p.text_field :price, id:"price", class: "form-control",
                            placeholder: "Price"%>
  </div>

  <P>
    <%= p.submit "Save", class:"btn btn-default"%>
  </P>

<% end %>

app/views/partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "Brands", brands_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/products/_form.html.erb
<%= form_for @product do |p| %>

  <% if @product.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@product.errors.count, "error") %>.
      </div>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="form-group col-md-6">
      <%= p.label :name, for: "name" %>
      <%= p.text_field :name, id:"name", class: "form-control",
                              placeholder: "Name"%>
    </div>

    <div class="form-group col-md-6">
      <%= p.label :brand, for: "brand" %>
      <%= p.collection_select :brand_id, Brand.all, :id, :name, {prompt: 'Please select a brand'},
                              {class: "form-control"}%>

    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-12">
      <%= p.label :descriptions, for: "description" %>
      <%= p.text_area :description, id:"description", class: "form-control",
                              placeholder: "Description"%>
    </div>
  </div>


    <div class="form-group">
      <%= p.label :price, for: "price" %>
      <%= p.text_field :price, step:"any", id:"price", class: "form-control",
                              placeholder: "Price"%>
    </div>

    <P>
      <%= p.submit "Save", class:"btn btn-default"%>
    </P>

<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div>
    <h1>Editing <%= @product.name %></h1>
    <%= link_to 'Back', product_path %>
    <hr>
  </div>

  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/products/index.html.erb
<div class="row">

  <div class="form-group col-md-6">
    <h1 class="text-title" >Products list</h1>
    <%= link_to "Add Product", new_product_path %>
  </div>

  <div class="form-group col-md-6">
    <h2 class="text-title">Sum of prices: <mark><%= @total.round(2) %></mark></h2>
  </div>
</div>

<div class="row">
  <div>
    <% @products.each do |p| %>
      <hr>
      <u class="text-uppercase"><%= link_to p.name, p%></u><br>
      <%= p.brand.name %><br />
      <%= p.description %><br />
      <%= p.price %><br />
      <br>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="row">
  <div>
    <h1>Create Product</h1>
    <%= link_to 'Back', products_path %>
    <hr>
  </div>

  <div>
    <%= render 'form' %>
  </div>
</div>

app/views/products/show.html.erb
<div class="row">
  <div class="margin-bottom">
    <h1>Product "<%= @product.name %>"</h1>
    <%= link_to 'Products list', products_path %> | <%= link_to 'Edit', edit_product_path %> |
    <%= link_to 'Delete', @product, method: :delete, data: { confirm: 'Are you sure to delete this product?' }%>
    <hr>
  </div>

  <div>
    <p>
      <%= @product.name %><br />
      <%= @product.brand.name %><br />
      <%= @product.description %><br />
      <%= @product.price %><br />
    </p>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">Welcome to TestApp</h1>
  </div>
</div>